const List<Map<String, dynamic>> countryLists = [
  {"country_code": "HK", "country_en": "Hong Kong", "phone_code": 852, "timezone": "Asia/Hong_Kong", "flag": "flags/hk.png"},
  {"country_code": "US", "country_en": "United States", "phone_code": 1, "timezone": "Pacific/Honolulu", "flag": "flags/us.png"},
  {"country_code": "AL", "country_en": "Albania", "phone_code": 355, "timezone": "Europe/Tirane", "flag": "flags/al.png"},
  {"country_code": "DZ", "country_en": "Algeria", "phone_code": 213, "timezone": "Africa/Algiers", "flag": "flags/dz.png"},
  {"country_code": "AF", "country_en": "Afghanistan", "phone_code": 93, "timezone": "Asia/Kabul", "flag": "flags/af.png"},
  {"country_code": "AR", "country_en": "Argentina", "phone_code": 54, "timezone": "America/Argentina/Ushuaia", "flag": "flags/ar.png"},
  {"country_code": "AE", "country_en": "United Arab Emirates", "phone_code": 971, "timezone": "Asia/Dubai", "flag": "flags/ae.png"},
  {"country_code": "AW", "country_en": "Aruba", "phone_code": 297, "timezone": "America/Aruba", "flag": "flags/aw.png"},
  {"country_code": "OM", "country_en": "Oman", "phone_code": 968, "timezone": "Asia/Muscat", "flag": "flags/om.png"},
  {"country_code": "AZ", "country_en": "Azerbaijan", "phone_code": 994, "timezone": "Asia/Baku", "flag": "flags/az.png"},
  {"country_code": "EG", "country_en": "Egypt", "phone_code": 20, "timezone": "Africa/Cairo", "flag": "flags/eg.png"},
  {"country_code": "ET", "country_en": "Ethiopia", "phone_code": 251, "timezone": "Africa/Addis_Ababa", "flag": "flags/et.png"},
  {"country_code": "IE", "country_en": "Ireland", "phone_code": 353, "timezone": "Europe/Dublin", "flag": "flags/ie.png"},
  {"country_code": "EE", "country_en": "Estonia", "phone_code": 372, "timezone": "Europe/Tallinn", "flag": "flags/ee.png"},
  {"country_code": "AD", "country_en": "Andorra", "phone_code": 376, "timezone": "Europe/Andorra", "flag": "flags/ad.png"},
  {"country_code": "AO", "country_en": "Angola", "phone_code": 244, "timezone": "Africa/Luanda", "flag": "flags/ao.png"},
  {"country_code": "AI", "country_en": "Anguilla", "phone_code": 1264, "timezone": "America/Anguilla", "flag": "flags/ai.png"},
  {"country_code": "AG", "country_en": "Antigua", "phone_code": 1268, "timezone": "America/Antigua", "flag": "flags/ag.png"},
  {"country_code": "AT", "country_en": "Austria", "phone_code": 43, "timezone": "Europe/Vienna", "flag": "flags/at.png"},
  {"country_code": "AU", "country_en": "Australia", "phone_code": 61, "timezone": "Australia/Sydney", "flag": "flags/au.png"},
  {"country_code": "MO", "country_en": "Macau", "phone_code": 853, "timezone": "Asia/Macau", "flag": "flags/mo.png"},
  {"country_code": "BB", "country_en": "Barbados", "phone_code": 1246, "timezone": "America/Barbados", "flag": "flags/bb.png"},
  {"country_code": "PG", "country_en": "Papua New Guinea", "phone_code": 675, "timezone": "Pacific/Port_Moresby", "flag": "flags/pg.png"},
  {"country_code": "BS", "country_en": "The Bahamas", "phone_code": 1242, "timezone": "America/Nassau", "flag": "flags/bs.png"},
  {"country_code": "PK", "country_en": "Pakistan", "phone_code": 92, "timezone": "Asia/Karachi", "flag": "flags/pk.png"},
  {"country_code": "PY", "country_en": "Paraguay", "phone_code": 595, "timezone": "America/Asuncion", "flag": "flags/py.png"},
  {"country_code": "PS", "country_en": "Palestine", "phone_code": 970, "timezone": "Asia/Hebron", "flag": "flags/ps.png"},
  {"country_code": "BH", "country_en": "Bahrain", "phone_code": 973, "timezone": "Asia/Bahrain", "flag": "flags/bh.png"},
  {"country_code": "PA", "country_en": "Panama", "phone_code": 507, "timezone": "America/Panama", "flag": "flags/pa.png"},
  {"country_code": "BR", "country_en": "Brazil", "phone_code": 55, "timezone": "America/Sao_Paulo", "flag": "flags/br.png"},
  {"country_code": "BY", "country_en": "Belarus", "phone_code": 375, "timezone": "Europe/Minsk", "flag": "flags/by.png"},
  {"country_code": "BM", "country_en": "Bermuda", "phone_code": 1441, "timezone": "Atlantic/Bermuda", "flag": "flags/bm.png"},
  {"country_code": "BG", "country_en": "Bulgaria", "phone_code": 359, "timezone": "Europe/Sofia", "flag": "flags/bg.png"},
  {"country_code": "MP", "country_en": "Northern Mariana Islands", "phone_code": 1670, "timezone": "Pacific/Saipan", "flag": "flags/mp.png"},
  {"country_code": "BJ", "country_en": "Benin", "phone_code": 229, "timezone": "Africa/Porto", "flag": "flags/bj.png"},
  {"country_code": "BE", "country_en": "Belgium", "phone_code": 32, "timezone": "Europe/Brussels", "flag": "flags/be.png"},
  {"country_code": "IS", "country_en": "Iceland", "phone_code": 354, "timezone": "Atlantic/Reykjavik", "flag": "flags/is.png"},
  {"country_code": "PL", "country_en": "Poland", "phone_code": 48, "timezone": "Europe/Warsaw", "flag": "flags/pl.png"},
  {"country_code": "BA", "country_en": "Bosnia and Herzegovina", "phone_code": 387, "timezone": "Europe/Sarajevo", "flag": "flags/ba.png"},
  {"country_code": "BO", "country_en": "Bolivia", "phone_code": 591, "timezone": "America/La_Paz", "flag": "flags/bo.png"},
  {"country_code": "BZ", "country_en": "Belize", "phone_code": 501, "timezone": "America/Belize", "flag": "flags/bz.png"},
  {"country_code": "PW", "country_en": "Palau", "phone_code": 680, "timezone": "Pacific/Palau", "flag": "flags/pw.png"},
  {"country_code": "BW", "country_en": "Botswana", "phone_code": 267, "timezone": "Africa/Gaborone", "flag": "flags/bw.png"},
  {"country_code": "BT", "country_en": "Bhutan", "phone_code": 975, "timezone": "Asia/Thimphu", "flag": "flags/bt.png"},
  {"country_code": "BF", "country_en": "Burkina Faso", "phone_code": 226, "timezone": "Africa/Ouagadougou", "flag": "flags/bf.png"},
  {"country_code": "BI", "country_en": "Burundi", "phone_code": 257, "timezone": "Africa/Bujumbura", "flag": "flags/bi.png"},
  {"country_code": "KP", "country_en": "North Korea", "phone_code": 850, "timezone": "Asia/Pyongyang", "flag": "flags/kp.png"},
  {"country_code": "GQ", "country_en": "Equatorial Guinea", "phone_code": 240, "timezone": "Africa/Malabo", "flag": "flags/gq.png"},
  {"country_code": "DK", "country_en": "Denmark", "phone_code": 45, "timezone": "Europe/Copenhagen", "flag": "flags/dk.png"},
  {"country_code": "DE", "country_en": "Germany", "phone_code": 49, "timezone": "Europe/Busingen", "flag": "flags/de.png"},
  {"country_code": "TL", "country_en": "Timor-Leste", "phone_code": 670, "timezone": "Asia/Dili", "flag": "flags/tl.png"},
  {"country_code": "TG", "country_en": "Togo", "phone_code": 228, "timezone": "Africa/Lome", "flag": "flags/tg.png"},
  {"country_code": "DM", "country_en": "Dominica", "phone_code": 1767, "timezone": "America/Dominica", "flag": "flags/dm.png"},
  {"country_code": "DO", "country_en": "Dominican Republic", "phone_code": 1809, "timezone": "America/Santo_Domingo", "flag": "flags/do.png"},
  {"country_code": "RU", "country_en": "Russia", "phone_code": 7, "timezone": "Europe/Volgograd", "flag": "flags/ru.png"},
  {"country_code": "EC", "country_en": "Ecuador", "phone_code": 593, "timezone": "Pacific/Galapagos", "flag": "flags/ec.png"},
  {"country_code": "ER", "country_en": "Eritrea", "phone_code": 291, "timezone": "Africa/Asmara", "flag": "flags/er.png"},
  {"country_code": "FR", "country_en": "France", "phone_code": 33, "timezone": "Europe/Paris", "flag": "flags/fr.png"},
  {"country_code": "FO", "country_en": "Faroe Islands", "phone_code": 298, "timezone": "Atlantic/Faroe", "flag": "flags/fo.png"},
  {"country_code": "PF", "country_en": "French Polynesia", "phone_code": 689, "timezone": "Pacific/Tahiti", "flag": "flags/pf.png"},
  {"country_code": "GF", "country_en": "French Guiana", "phone_code": 594, "timezone": "America/Cayenne", "flag": "flags/gf.png"},
  {"country_code": "PM", "country_en": "Saint Pierre and Miquelon", "phone_code": 508, "timezone": "America/Miquelon", "flag": "flags/pm.png"},
  {"country_code": "VA", "country_en": "Vatican City", "phone_code": 39, "timezone": "Europe/Vatican", "flag": "flags/va.png"},
  {"country_code": "PH", "country_en": "Philippines", "phone_code": 63, "timezone": "Asia/Manila", "flag": "flags/ph.png"},
  {"country_code": "FJ", "country_en": "Fiji", "phone_code": 679, "timezone": "Pacific/Fiji", "flag": "flags/fj.png"},
  {"country_code": "FI", "country_en": "Finland", "phone_code": 358, "timezone": "Europe/Helsinki", "flag": "flags/fi.png"},
  {"country_code": "CV", "country_en": "Cape Verde", "phone_code": 238, "timezone": "Atlantic/Cape_Verde", "flag": "flags/cv.png"},
  {"country_code": "FK", "country_en": "Falkland Islands", "phone_code": 500, "timezone": "Atlantic/Stanley", "flag": "flags/fk.png"},
  {"country_code": "GM", "country_en": "The Gambia", "phone_code": 220, "timezone": "Africa/Banjul", "flag": "flags/gm.png"},
  {"country_code": "CG", "country_en": "Republic of the Congo", "phone_code": 242, "timezone": "Africa/Brazzaville", "flag": "flags/cg.png"},
  {"country_code": "CD", "country_en": "Democratic Republic of the Congo", "phone_code": 243, "timezone": "Africa/Lubumbashi", "flag": "flags/cd.png"},
  {"country_code": "CO", "country_en": "Colombia", "phone_code": 57, "timezone": "America/Bogota", "flag": "flags/co.png"},
  {"country_code": "CR", "country_en": "Costa Rica", "phone_code": 506, "timezone": "America/Costa_Rica", "flag": "flags/cr.png"},
  {"country_code": "GD", "country_en": "Grenada", "phone_code": 1473, "timezone": "America/Grenada", "flag": "flags/gd.png"},
  {"country_code": "GL", "country_en": "Greenland", "phone_code": 299, "timezone": "America/Thule", "flag": "flags/gl.png"},
  {"country_code": "GE", "country_en": "Georgia", "phone_code": 995, "timezone": "Asia/Tbilisi", "flag": "flags/ge.png"},
  {"country_code": "GG", "country_en": "Guernsey", "phone_code": 44, "timezone": "Europe/Guernsey", "flag": "flags/gg.png"},
  {"country_code": "CU", "country_en": "Cuba", "phone_code": 53, "timezone": "America/Havana", "flag": "flags/cu.png"},
  {"country_code": "GP", "country_en": "Guadeloupe", "phone_code": 590, "timezone": "America/Guadeloupe", "flag": "flags/gp.png"},
  {"country_code": "GU", "country_en": "Guam", "phone_code": 1671, "timezone": "Pacific/Guam", "flag": "flags/gu.png"},
  {"country_code": "GY", "country_en": "Guyana", "phone_code": 592, "timezone": "America/Guyana", "flag": "flags/gy.png"},
  {"country_code": "KZ", "country_en": "Kazakhstan", "phone_code": 7, "timezone": "Asia/Qyzylorda", "flag": "flags/kz.png"},
  {"country_code": "HT", "country_en": "Haiti", "phone_code": 509, "timezone": "America/Port", "flag": "flags/ht.png"},
  {"country_code": "KR", "country_en": "South Korea", "phone_code": 82, "timezone": "Asia/Seoul", "flag": "flags/kr.png"},
  {"country_code": "NL", "country_en": "Netherlands", "phone_code": 31, "timezone": "Europe/Amsterdam", "flag": "flags/nl.png"},
  {"country_code": "BQ", "country_en": "Bonaire, Sint Eustatius and Saba", "phone_code": 599, "timezone": "America/Kralendijk", "flag": "flags/bq.png"},
  {"country_code": "ME", "country_en": "Montenegro", "phone_code": 382, "timezone": "Europe/Podgorica", "flag": "flags/me.png"},
  {"country_code": "HN", "country_en": "Honduras", "phone_code": 504, "timezone": "America/Tegucigalpa", "flag": "flags/hn.png"},
  {"country_code": "KI", "country_en": "Kiribati", "phone_code": 686, "timezone": "Pacific/Tarawa", "flag": "flags/ki.png"},
  {"country_code": "DJ", "country_en": "Djibouti", "phone_code": 253, "timezone": "Africa/Djibouti", "flag": "flags/dj.png"},
  {"country_code": "KG", "country_en": "Kyrgyzstan", "phone_code": 996, "timezone": "Asia/Bishkek", "flag": "flags/kg.png"},
  {"country_code": "GN", "country_en": "Guinea", "phone_code": 224, "timezone": "Africa/Conakry", "flag": "flags/gn.png"},
  {"country_code": "GW", "country_en": "Guinea-Bissau", "phone_code": 245, "timezone": "Africa/Bissau", "flag": "flags/gw.png"},
  {"country_code": "GH", "country_en": "Ghana", "phone_code": 233, "timezone": "Africa/Accra", "flag": "flags/gh.png"},
  {"country_code": "GA", "country_en": "Gabon", "phone_code": 241, "timezone": "Africa/Libreville", "flag": "flags/ga.png"},
  {"country_code": "KH", "country_en": "Cambodia", "phone_code": 855, "timezone": "Asia/Phnom_Penh", "flag": "flags/kh.png"},
  {"country_code": "CZ", "country_en": "Czech Republic", "phone_code": 420, "timezone": "Europe/Prague", "flag": "flags/cz.png"},
  {"country_code": "ZW", "country_en": "Zimbabwe", "phone_code": 263, "timezone": "Africa/Harare", "flag": "flags/zw.png"},
  {"country_code": "CM", "country_en": "Cameroon", "phone_code": 237, "timezone": "Africa/Douala", "flag": "flags/cm.png"},
  {"country_code": "QA", "country_en": "Qatar", "phone_code": 974, "timezone": "Asia/Qatar", "flag": "flags/qa.png"},
  {"country_code": "KY", "country_en": "Cayman Islands", "phone_code": 1345, "timezone": "America/Cayman", "flag": "flags/ky.png"},
  {"country_code": "KM", "country_en": "Comoros", "phone_code": 269, "timezone": "Indian/Comoro", "flag": "flags/km.png"},
  {"country_code": "XK", "country_en": "Kosovo", "phone_code": 381, "timezone": null, "flag": "flags/xk.png"},
  {"country_code": "CI", "country_en": "Côte d'Ivoire", "phone_code": 225, "timezone": "Africa/Abidjan", "flag": "flags/ci.png"},
  {"country_code": "KW", "country_en": "Kuwait", "phone_code": 965, "timezone": "Asia/Kuwait", "flag": "flags/kw.png"},
  {"country_code": "HR", "country_en": "Croatia", "phone_code": 385, "timezone": "Europe/Zagreb", "flag": "flags/hr.png"},
  {"country_code": "KE", "country_en": "Kenya", "phone_code": 254, "timezone": "Africa/Nairobi", "flag": "flags/ke.png"},
  {"country_code": "CK", "country_en": "Cook Islands", "phone_code": 682, "timezone": "Pacific/Rarotonga", "flag": "flags/ck.png"},
  {"country_code": "CW", "country_en": "Curaçao", "phone_code": 599, "timezone": "America/Curacao", "flag": "flags/cw.png"},
  {"country_code": "LV", "country_en": "Latvia", "phone_code": 371, "timezone": "Europe/Riga", "flag": "flags/lv.png"},
  {"country_code": "LS", "country_en": "Lesotho", "phone_code": 266, "timezone": "Africa/Maseru", "flag": "flags/ls.png"},
  {"country_code": "LA", "country_en": "Laos", "phone_code": 856, "timezone": "Asia/Vientiane", "flag": "flags/la.png"},
  {"country_code": "LB", "country_en": "Lebanon", "phone_code": 961, "timezone": "Asia/Beirut", "flag": "flags/lb.png"},
  {"country_code": "LT", "country_en": "Lithuania", "phone_code": 370, "timezone": "Europe/Vilnius", "flag": "flags/lt.png"},
  {"country_code": "LR", "country_en": "Liberia", "phone_code": 231, "timezone": "Africa/Monrovia", "flag": "flags/lr.png"},
  {"country_code": "LY", "country_en": "Libya", "phone_code": 218, "timezone": "Africa/Tripoli", "flag": "flags/ly.png"},
  {"country_code": "LI", "country_en": "Liechtenstein", "phone_code": 423, "timezone": "Europe/Vaduz", "flag": "flags/li.png"},
  {"country_code": "RE", "country_en": "Réunion", "phone_code": 262, "timezone": "Indian/Reunion", "flag": "flags/re.png"},
  {"country_code": "LU", "country_en": "Luxembourg", "phone_code": 352, "timezone": "Europe/Luxembourg", "flag": "flags/lu.png"},
  {"country_code": "RW", "country_en": "Rwanda", "phone_code": 250, "timezone": "Africa/Kigali", "flag": "flags/rw.png"},
  {"country_code": "RO", "country_en": "Romania", "phone_code": 40, "timezone": "Europe/Bucharest", "flag": "flags/ro.png"},
  {"country_code": "MG", "country_en": "Madagascar", "phone_code": 261, "timezone": "Indian/Antananarivo", "flag": "flags/mg.png"},
  {"country_code": "IM", "country_en": "Isle Of Man", "phone_code": 44, "timezone": "Europe/Isle_of_Man", "flag": "flags/im.png"},
  {"country_code": "MV", "country_en": "Maldives", "phone_code": 960, "timezone": "Indian/Maldives", "flag": "flags/mv.png"},
  {"country_code": "MT", "country_en": "Malta", "phone_code": 356, "timezone": "Europe/Malta", "flag": "flags/mt.png"},
  {"country_code": "MW", "country_en": "Malawi", "phone_code": 265, "timezone": "Africa/Blantyre", "flag": "flags/mw.png"},
  {"country_code": "MY", "country_en": "Malaysia", "phone_code": 60, "timezone": "Asia/Kuching", "flag": "flags/my.png"},
  {"country_code": "ML", "country_en": "Mali", "phone_code": 223, "timezone": "Africa/Bamako", "flag": "flags/ml.png"},
  {"country_code": "MK", "country_en": "Macedonia", "phone_code": 389, "timezone": "Europe/Skopje", "flag": "flags/mk.png"},
  {"country_code": "MH", "country_en": "Marshall Islands", "phone_code": 692, "timezone": "Pacific/Majuro", "flag": "flags/mh.png"},
  {"country_code": "MQ", "country_en": "Martinique", "phone_code": 596, "timezone": "America/Martinique", "flag": "flags/mq.png"},
  {"country_code": "YT", "country_en": "Mayotte", "phone_code": 262, "timezone": "Indian/Mayotte", "flag": "flags/yt.png"},
  {"country_code": "MU", "country_en": "Mauritius", "phone_code": 230, "timezone": "Indian/Mauritius", "flag": "flags/mu.png"},
  {"country_code": "MR", "country_en": "Mauritania", "phone_code": 222, "timezone": "Africa/Nouakchott", "flag": "flags/mr.png"},
  {"country_code": "AS", "country_en": "American Samoa", "phone_code": 1684, "timezone": "Pacific/Pago_Pago", "flag": "flags/as.png"},
  {"country_code": "VI", "country_en": "US Virgin Islands", "phone_code": 1340, "timezone": "America/St_Thomas", "flag": "flags/vi.png"},
  {"country_code": "MN", "country_en": "Mongolia", "phone_code": 976, "timezone": "Asia/Ulaanbaatar", "flag": "flags/mn.png"},
  {"country_code": "MS", "country_en": "Montserrat", "phone_code": 1664, "timezone": "America/Montserrat", "flag": "flags/ms.png"},
  {"country_code": "BD", "country_en": "Bangladesh", "phone_code": 880, "timezone": "Asia/Dhaka", "flag": "flags/bd.png"},
  {"country_code": "PE", "country_en": "Peru", "phone_code": 51, "timezone": "America/Lima", "flag": "flags/pe.png"},
  {"country_code": "FM", "country_en": "Federated States of Micronesia", "phone_code": 691, "timezone": "Pacific/Pohnpei", "flag": "flags/fm.png"},
  {"country_code": "MM", "country_en": "Myanmar", "phone_code": 95, "timezone": "Asia/Yangon", "flag": "flags/mm.png"},
  {"country_code": "MD", "country_en": "Moldova", "phone_code": 373, "timezone": "Europe/Chisinau", "flag": "flags/md.png"},
  {"country_code": "MA", "country_en": "Morocco", "phone_code": 212, "timezone": "Africa/Casablanca", "flag": "flags/ma.png"},
  {"country_code": "MC", "country_en": "Monaco", "phone_code": 377, "timezone": "Europe/Monaco", "flag": "flags/mc.png"},
  {"country_code": "MZ", "country_en": "Mozambique", "phone_code": 258, "timezone": "Africa/Maputo", "flag": "flags/mz.png"},
  {"country_code": "MX", "country_en": "Mexico", "phone_code": 52, "timezone": "America/Tijuana", "flag": "flags/mx.png"},
  {"country_code": "NA", "country_en": "Namibia", "phone_code": 264, "timezone": "Africa/Windhoek", "flag": "flags/na.png"},
  {"country_code": "ZA", "country_en": "South Africa", "phone_code": 27, "timezone": "Africa/Johannesburg", "flag": "flags/za.png"},
  {"country_code": "SS", "country_en": "South Sudan", "phone_code": 211, "timezone": "Africa/Juba", "flag": "flags/ss.png"},
  {"country_code": "NR", "country_en": "Nauru", "phone_code": 674, "timezone": "Pacific/Nauru", "flag": "flags/nr.png"},
  {"country_code": "NI", "country_en": "Nicaragua", "phone_code": 505, "timezone": "America/Managua", "flag": "flags/ni.png"},
  {"country_code": "NP", "country_en": "Nepal", "phone_code": 977, "timezone": "Asia/Kathmandu", "flag": "flags/np.png"},
  {"country_code": "NE", "country_en": "Niger", "phone_code": 227, "timezone": "Africa/Niamey", "flag": "flags/ne.png"},
  {"country_code": "NG", "country_en": "Nigeria", "phone_code": 234, "timezone": "Africa/Lagos", "flag": "flags/ng.png"},
  {"country_code": "NU", "country_en": "Niue", "phone_code": 683, "timezone": "Pacific/Niue", "flag": "flags/nu.png"},
  {"country_code": "NO", "country_en": "Norway", "phone_code": 47, "timezone": "Europe/Oslo", "flag": "flags/no.png"},
  {"country_code": "NF", "country_en": "Norfolk Island", "phone_code": 672, "timezone": "Pacific/Norfolk", "flag": "flags/nf.png"},
  {"country_code": "PT", "country_en": "Portugal", "phone_code": 351, "timezone": "Europe/Lisbon", "flag": "flags/pt.png"},
  {"country_code": "JP", "country_en": "Japan", "phone_code": 81, "timezone": "Asia/Tokyo", "flag": "flags/jp.png"},
  {"country_code": "SE", "country_en": "Sweden", "phone_code": 46, "timezone": "Europe/Stockholm", "flag": "flags/se.png"},
  {"country_code": "CH", "country_en": "Switzerland", "phone_code": 41, "timezone": "Europe/Zurich", "flag": "flags/ch.png"},
  {"country_code": "SV", "country_en": "El Salvador", "phone_code": 503, "timezone": "America/El_Salvador", "flag": "flags/sv.png"},
  {"country_code": "WS", "country_en": "Samoa", "phone_code": 685, "timezone": "Pacific/Apia", "flag": "flags/ws.png"},
  {"country_code": "RS", "country_en": "Serbia", "phone_code": 381, "timezone": "Europe/Belgrade", "flag": "flags/rs.png"},
  {"country_code": "SL", "country_en": "Sierra Leone", "phone_code": 232, "timezone": "Africa/Freetown", "flag": "flags/sl.png"},
  {"country_code": "SN", "country_en": "Senegal", "phone_code": 221, "timezone": "Africa/Dakar", "flag": "flags/sn.png"},
  {"country_code": "CY", "country_en": "Cyprus", "phone_code": 357, "timezone": "Asia/Nicosia", "flag": "flags/cy.png"},
  {"country_code": "SC", "country_en": "Seychelles", "phone_code": 248, "timezone": "Indian/Mahe", "flag": "flags/sc.png"},
  {"country_code": "SA", "country_en": "Saudi Arabia", "phone_code": 966, "timezone": "Asia/Riyadh", "flag": "flags/sa.png"},
  {"country_code": "BL", "country_en": "Saint Barthélemy", "phone_code": 590, "timezone": "America/St_Barthelemy", "flag": "flags/bl.png"},
  {"country_code": "ST", "country_en": "Sao Tome and Principe", "phone_code": 239, "timezone": "Africa/Sao_Tome", "flag": "flags/st.png"},
  {"country_code": "SH", "country_en": "Saint Helena", "phone_code": 290, "timezone": "Atlantic/St_Helena", "flag": "flags/sh.png"},
  {"country_code": "KN", "country_en": "Saint Kitts and Nevis", "phone_code": 1869, "timezone": "America/St_Kitts", "flag": "flags/kn.png"},
  {"country_code": "LC", "country_en": "Saint Lucia", "phone_code": 1758, "timezone": "America/St_Lucia", "flag": "flags/lc.png"},
  {"country_code": "MF", "country_en": "Saint Martin", "phone_code": 590, "timezone": "America/Marigot", "flag": "flags/mf.png"},
  {"country_code": "SX", "country_en": "Sint Maarten", "phone_code": 599, "timezone": "America/Lower_Princes", "flag": "flags/sx.png"},
  {"country_code": "SM", "country_en": "San Marino", "phone_code": 378, "timezone": "Europe/San_Marino", "flag": "flags/sm.png"},
  {"country_code": "VC", "country_en": "Saint Vincent and the Grenadines", "phone_code": 1784, "timezone": "America/St_Vincent", "flag": "flags/vc.png"},
  {"country_code": "LK", "country_en": "Sri Lanka", "phone_code": 94, "timezone": "Asia/Colombo", "flag": "flags/lk.png"},
  {"country_code": "SK", "country_en": "Slovakia", "phone_code": 421, "timezone": "Europe/Bratislava", "flag": "flags/sk.png"},
  {"country_code": "SI", "country_en": "Slovenia", "phone_code": 386, "timezone": "Europe/Ljubljana", "flag": "flags/si.png"},
  {"country_code": "SZ", "country_en": "Swaziland", "phone_code": 268, "timezone": "Africa/Mbabane", "flag": "flags/sz.png"},
  {"country_code": "SD", "country_en": "Sudan", "phone_code": 249, "timezone": "Africa/Khartoum", "flag": "flags/sd.png"},
  {"country_code": "SR", "country_en": "Suriname", "phone_code": 597, "timezone": "America/Paramaribo", "flag": "flags/sr.png"},
  {"country_code": "SB", "country_en": "Solomon Islands", "phone_code": 677, "timezone": "Pacific/Guadalcanal", "flag": "flags/sb.png"},
  {"country_code": "SO", "country_en": "Somalia", "phone_code": 252, "timezone": "Africa/Mogadishu", "flag": "flags/so.png"},
  {"country_code": "TJ", "country_en": "Tajikistan", "phone_code": 992, "timezone": "Asia/Dushanbe", "flag": "flags/tj.png"},
  {"country_code": "TW", "country_en": "Taiwan", "phone_code": 886, "timezone": "Asia/Taipei", "flag": "flags/tw.png"},
  {"country_code": "TH", "country_en": "Thailand", "phone_code": 66, "timezone": "Asia/Bangkok", "flag": "flags/th.png"},
  {"country_code": "timezone", "country_en": "Tanzania", "phone_code": 255, "timezone": "Africa/Dar_es_Salaam", "flag": "flags/tz.png"},
  {"country_code": "TO", "country_en": "Tonga", "phone_code": 676, "timezone": "Pacific/Tongatapu", "flag": "flags/to.png"},
  {"country_code": "TC", "country_en": "Turks and Caicos Islands", "phone_code": 1649, "timezone": "America/Grand_Turk", "flag": "flags/tc.png"},
  {"country_code": "TT", "country_en": "Trinidad and Tobago", "phone_code": 1868, "timezone": "America/Port_of_Spain", "flag": "flags/tt.png"},
  {"country_code": "TN", "country_en": "Tunisia", "phone_code": 216, "timezone": "Africa/Tunis", "flag": "flags/tn.png"},
  {"country_code": "TV", "country_en": "Tuvalu", "phone_code": 688, "timezone": "Pacific/Funafuti", "flag": "flags/tv.png"},
  {"country_code": "TR", "country_en": "Turkey", "phone_code": 90, "timezone": "Europe/Istanbul", "flag": "flags/tr.png"},
  {"country_code": "TM", "country_en": "Turkmenistan", "phone_code": 993, "timezone": "Asia/Ashgabat", "flag": "flags/tm.png"},
  {"country_code": "TK", "country_en": "Tokelau", "phone_code": 690, "timezone": "Pacific/Fakaofo", "flag": "flags/tk.png"},
  {"country_code": "WF", "country_en": "Wallis and Futuna", "phone_code": 681, "timezone": "Pacific/Wallis", "flag": "flags/wf.png"},
  {"country_code": "VU", "country_en": "Vanuatu", "phone_code": 678, "timezone": "Pacific/Efate", "flag": "flags/vu.png"},
  {"country_code": "GT", "country_en": "Guatemala", "phone_code": 502, "timezone": "America/Guatemala", "flag": "flags/gt.png"},
  {"country_code": "VE", "country_en": "Venezuela", "phone_code": 58, "timezone": "America/Caracas", "flag": "flags/ve.png"},
  {"country_code": "BN", "country_en": "Brunei", "phone_code": 673, "timezone": "Asia/Brunei", "flag": "flags/bn.png"},
  {"country_code": "UG", "country_en": "Uganda", "phone_code": 256, "timezone": "Africa/Kampala", "flag": "flags/ug.png"},
  {"country_code": "UA", "country_en": "Ukraine", "phone_code": 380, "timezone": "Europe/Zaporozhye", "flag": "flags/ua.png"},
  {"country_code": "UY", "country_en": "Uruguay", "phone_code": 598, "timezone": "America/Montevideo", "flag": "flags/uy.png"},
  {"country_code": "UZ", "country_en": "Uzbekistan", "phone_code": 998, "timezone": "Asia/Tashkent", "flag": "flags/uz.png"},
  {"country_code": "GR", "country_en": "Greece", "phone_code": 30, "timezone": "Europe/Athens", "flag": "flags/gr.png"},
  {"country_code": "ES", "country_en": "Spain", "phone_code": 34, "timezone": "Europe/Madrid", "flag": "flags/es.png"},
  {"country_code": "EH", "country_en": "Western Sahara", "phone_code": 212, "timezone": "Africa/El_Aaiun", "flag": "flags/eh.png"},
  {"country_code": "SG", "country_en": "Singapore", "phone_code": 65, "timezone": "Asia/Singapore", "flag": "flags/sg.png"},
  {"country_code": "NC", "country_en": "New Caledonia", "phone_code": 687, "timezone": "Pacific/Noumea", "flag": "flags/nc.png"},
  {"country_code": "NZ", "country_en": "New Zealand", "phone_code": 64, "timezone": "Pacific/Chatham", "flag": "flags/nz.png"},
  {"country_code": "HU", "country_en": "Hungary", "phone_code": 36, "timezone": "Europe/Budapest", "flag": "flags/hu.png"},
  {"country_code": "SY", "country_en": "Syria", "phone_code": 963, "timezone": "Asia/Damascus", "flag": "flags/sy.png"},
  {"country_code": "JM", "country_en": "Jamaica", "phone_code": 1876, "timezone": "America/Jamaica", "flag": "flags/jm.png"},
  {"country_code": "AM", "country_en": "Armenia", "phone_code": 374, "timezone": "Asia/Yerevan", "flag": "flags/am.png"},
  {"country_code": "YE", "country_en": "Yemen", "phone_code": 967, "timezone": "Asia/Aden", "flag": "flags/ye.png"},
  {"country_code": "IQ", "country_en": "Iraq", "phone_code": 964, "timezone": "Asia/Baghdad", "flag": "flags/iq.png"},
  {"country_code": "IR", "country_en": "Iran", "phone_code": 98, "timezone": "Asia/Tehran", "flag": "flags/ir.png"},
  {"country_code": "IL", "country_en": "Israel", "phone_code": 972, "timezone": "Asia/Jerusalem", "flag": "flags/il.png"},
  {"country_code": "IT", "country_en": "Italy", "phone_code": 39, "timezone": "Europe/Rome", "flag": "flags/it.png"},
  {"country_code": "IN", "country_en": "India", "phone_code": 91, "timezone": "Asia/Kolkata", "flag": "flags/in.png"},
  {"country_code": "ID", "country_en": "Indonesia", "phone_code": 62, "timezone": "Asia/Pontianak", "flag": "flags/id.png"},
  {"country_code": "GB", "country_en": "United Kingdom", "phone_code": 44, "timezone": "Europe/London", "flag": "flags/gb.png"},
  {"country_code": "VG", "country_en": "British Virgin Islands", "phone_code": 1284, "timezone": "America/Tortola", "flag": "flags/vg.png"},
  {"country_code": "IO", "country_en": "British Indian Ocean Territory", "phone_code": 246, "timezone": "Indian/Chagos", "flag": "flags/io.png"},
  {"country_code": "JO", "country_en": "Jordan", "phone_code": 962, "timezone": "Asia/Amman", "flag": "flags/jo.png"},
  {"country_code": "VN", "country_en": "Vietnam", "phone_code": 84, "timezone": "Asia/Ho_Chi_Minh", "flag": "flags/vn.png"},
  {"country_code": "ZM", "country_en": "Zambia", "phone_code": 260, "timezone": "Africa/Lusaka", "flag": "flags/zm.png"},
  {"country_code": "JE", "country_en": "Jersey", "phone_code": 44, "timezone": "Europe/Jersey", "flag": "flags/je.png"},
  {"country_code": "TD", "country_en": "Chad", "phone_code": 235, "timezone": "Africa/Ndjamena", "flag": "flags/td.png"},
  {"country_code": "GI", "country_en": "Gibraltar", "phone_code": 350, "timezone": "Europe/Gibraltar", "flag": "flags/gi.png"},
  {"country_code": "CL", "country_en": "Chile", "phone_code": 56, "timezone": "Pacific/Easter", "flag": "flags/cl.png"},
  {"country_code": "CF", "country_en": "Central African Republic", "phone_code": 236, "timezone": "Africa/Bangui", "flag": "flags/cf.png"},
  {"country_code": "CN", "country_en": "China", "phone_code": 86, "timezone": "Asia/Urumqi", "flag": "flags/cn.png"}
];

List<Map<String, dynamic>> countryList = [
  {"country_en": "Afghanistan", "flag": "🇦🇫", "country_code": "AF", "phone_code": 93, "min_length": 9, "max_length": 9},
  {"country_en": "Åland Islands", "flag": "🇦🇽", "country_code": "AX", "phone_code": 358, "min_length": 8, "max_length": 10},
  {"country_en": "Albania", "flag": "🇦🇱", "country_code": "AL", "phone_code": 355, "min_length": 9, "max_length": 9},
  {"country_en": "Algeria", "flag": "🇩🇿", "country_code": "DZ", "phone_code": 213, "min_length": 4, "max_length": 4},
  {"country_en": "American Samoa", "flag": "🇦🇸", "country_code": "AS", "phone_code": 1684, "min_length": 10, "max_length": 10},
  {"country_en": "Andorra", "flag": "🇦🇩", "country_code": "AD", "phone_code": 376, "min_length": 6, "max_length": 6},
  {"country_en": "Angola", "flag": "🇦🇴", "country_code": "AO", "phone_code": 244, "min_length": 9, "max_length": 9},
  {"country_en": "Anguilla", "flag": "🇦🇮", "country_code": "AI", "phone_code": 1264, "min_length": 10, "max_length": 10},
  {"country_en": "Antarctica", "flag": "🇦🇶", "country_code": "AQ", "phone_code": 672, "min_length": 6, "max_length": 6},
  {"country_en": "Antigua and Barbuda", "flag": "🇦🇬", "country_code": "AG", "phone_code": 1268, "min_length": 10, "max_length": 10},
  {"country_en": "Argentina", "flag": "🇦🇷", "country_code": "AR", "phone_code": 54, "min_length": 10, "max_length": 10},
  {"country_en": "Armenia", "flag": "🇦🇲", "country_code": "AM", "phone_code": 374, "min_length": 8, "max_length": 8},
  {"country_en": "Aruba", "flag": "🇦🇼", "country_code": "AW", "phone_code": 297, "min_length": 7, "max_length": 7},
  {"country_en": "Australia", "flag": "🇦🇺", "country_code": "AU", "phone_code": 61, "min_length": 9, "max_length": 9},
  {"country_en": "Austria", "flag": "🇦🇹", "country_code": "AT", "phone_code": 43, "min_length": 10, "max_length": 10},
  {"country_en": "Azerbaijan", "flag": "🇦🇿", "country_code": "AZ", "phone_code": 994, "min_length": 9, "max_length": 9},
  {"country_en": "Bahamas", "flag": "🇧🇸", "country_code": "BS", "phone_code": 1242, "min_length": 10, "max_length": 10},
  {"country_en": "Bahrain", "flag": "🇧🇭", "country_code": "BH", "phone_code": 973, "min_length": 8, "max_length": 8},
  {"country_en": "Bangladesh", "flag": "🇧🇩", "country_code": "BD", "phone_code": 880, "min_length": 10, "max_length": 10},
  {"country_en": "Barbados", "flag": "🇧🇧", "country_code": "BB", "phone_code": 1246, "min_length": 10, "max_length": 10},
  {"country_en": "Belarus", "flag": "🇧🇾", "country_code": "BY", "phone_code": 375, "min_length": 9, "max_length": 9},
  {"country_en": "Belgium", "flag": "🇧🇪", "country_code": "BE", "phone_code": 32, "min_length": 9, "max_length": 9},
  {"country_en": "Belize", "flag": "🇧🇿", "country_code": "BZ", "phone_code": 501, "min_length": 7, "max_length": 7},
  {"country_en": "Benin", "flag": "🇧🇯", "country_code": "BJ", "phone_code": 229, "min_length": 6, "max_length": 9},
  {"country_en": "Bermuda", "flag": "🇧🇲", "country_code": "BM", "phone_code": 1441, "min_length": 10, "max_length": 10},
  {"country_en": "Bhutan", "flag": "🇧🇹", "country_code": "BT", "phone_code": 975, "min_length": 8, "max_length": 8},
  {"country_en": "Bolivia, Plurinational State of bolivia", "flag": "🇧🇴", "country_code": "BO", "phone_code": 591, "min_length": 8, "max_length": 8},
  {"country_en": "Bosnia and Herzegovina", "flag": "🇧🇦", "country_code": "BA", "phone_code": 387, "min_length": 8, "max_length": 8},
  {"country_en": "Botswana", "flag": "🇧🇼", "country_code": "BW", "phone_code": 267, "min_length": 8, "max_length": 8},
  {"country_en": "Bouvet Island", "flag": "🇧🇻", "country_code": "BV", "phone_code": 47, "min_length": 15, "max_length": 15},
  {"country_en": "Brazil", "flag": "🇧🇷", "country_code": "BR", "phone_code": 55, "min_length": 11, "max_length": 11},
  {"country_en": "British Indian Ocean Territory", "flag": "🇮🇴", "country_code": "IO", "phone_code": 246, "min_length": 7, "max_length": 7},
  {"country_en": "Brunei Darussalam", "flag": "🇧🇳", "country_code": "BN", "phone_code": 673, "min_length": 7, "max_length": 7},
  {"country_en": "Bulgaria", "flag": "🇧🇬", "country_code": "BG", "phone_code": 359, "min_length": 9, "max_length": 9},
  {"country_en": "Burkina Faso", "flag": "🇧🇫", "country_code": "BF", "phone_code": 226, "min_length": 8, "max_length": 8},
  {"country_en": "Burundi", "flag": "🇧🇮", "country_code": "BI", "phone_code": 257, "min_length": 7, "max_length": 7},
  {"country_en": "Cambodia", "flag": "🇰🇭", "country_code": "KH", "phone_code": 855, "min_length": 9, "max_length": 9},
  {"country_en": "Cameroon", "flag": "🇨🇲", "country_code": "CM", "phone_code": 237, "min_length": 9, "max_length": 9},
  {"country_en": "Canada", "flag": "🇨🇦", "country_code": "CA", "phone_code": 1, "min_length": 10, "max_length": 10},
  {"country_en": "Cape Verde", "flag": "🇨🇻", "country_code": "CV", "phone_code": 238, "min_length": 7, "max_length": 7},
  {"country_en": "Cayman Islands", "flag": "🇰🇾", "country_code": "KY", "phone_code": 1345, "min_length": 10, "max_length": 10},
  {"country_en": "Central African Republic", "flag": "🇨🇫", "country_code": "CF", "phone_code": 236, "min_length": 8, "max_length": 8},
  {"country_en": "Chad", "flag": "🇹🇩", "country_code": "TD", "phone_code": 235, "min_length": 8, "max_length": 8},
  {"country_en": "Chile", "flag": "🇨🇱", "country_code": "CL", "phone_code": 56, "min_length": 9, "max_length": 9},
  {"country_en": "China", "flag": "🇨🇳", "country_code": "CN", "phone_code": 86, "min_length": 12, "max_length": 12},
  {"country_en": "Christmas Island", "flag": "🇨🇽", "country_code": "CX", "phone_code": 61, "min_length": 15, "max_length": 15},
  {"country_en": "Cocos (Keeling) Islands", "flag": "🇨🇨", "country_code": "CC", "phone_code": 61, "min_length": 15, "max_length": 15},
  {"country_en": "Colombia", "flag": "🇨🇴", "country_code": "CO", "phone_code": 57, "min_length": 10, "max_length": 10},
  {"country_en": "Comoros", "flag": "🇰🇲", "country_code": "KM", "phone_code": 269, "min_length": 7, "max_length": 7},
  {"country_en": "Congo", "flag": "🇨🇬", "country_code": "CG", "phone_code": 242, "min_length": 7, "max_length": 7},
  {"country_en": "Congo, The Democratic Republic of the Congo", "flag": "🇨🇩", "country_code": "CD", "phone_code": 243, "min_length": 9, "max_length": 9},
  {"country_en": "Cook Islands", "flag": "🇨🇰", "country_code": "CK", "phone_code": 682, "min_length": 5, "max_length": 5},
  {"country_en": "Costa Rica", "flag": "🇨🇷", "country_code": "CR", "phone_code": 506, "min_length": 8, "max_length": 8},
  {"country_en": "Côte d'Ivoire", "flag": "🇨🇮", "country_code": "CI", "phone_code": 225, "min_length": 10, "max_length": 10},
  {"country_en": "Croatia", "flag": "🇭🇷", "country_code": "HR", "phone_code": 385, "min_length": 9, "max_length": 9},
  {"country_en": "Cuba", "flag": "🇨🇺", "country_code": "CU", "phone_code": 53, "min_length": 8, "max_length": 8},
  {"country_en": "Cyprus", "flag": "🇨🇾", "country_code": "CY", "phone_code": 357, "min_length": 8, "max_length": 8},
  {"country_en": "Czech Republic", "flag": "🇨🇿", "country_code": "CZ", "phone_code": 420, "min_length": 9, "max_length": 9},
  {"country_en": "Denmark", "flag": "🇩🇰", "country_code": "DK", "phone_code": 45, "min_length": 8, "max_length": 8},
  {"country_en": "Djibouti", "flag": "🇩🇯", "country_code": "DJ", "phone_code": 253, "min_length": 6, "max_length": 6},
  {"country_en": "Dominica", "flag": "🇩🇲", "country_code": "DM", "phone_code": 1767, "min_length": 10, "max_length": 10},
  {"country_en": "Dominican Republic", "flag": "🇩🇴", "country_code": "DO", "phone_code": 1829, "min_length": 10, "max_length": 10},
  {"country_en": "Ecuador", "flag": "🇪🇨", "country_code": "EC", "phone_code": 593, "min_length": 9, "max_length": 9},
  {"country_en": "Egypt", "flag": "🇪🇬", "country_code": "EG", "phone_code": 20, "min_length": 10, "max_length": 10},
  {"country_en": "El Salvador", "flag": "🇸🇻", "country_code": "SV", "phone_code": 503, "min_length": 8, "max_length": 8},
  {"country_en": "Equatorial Guinea", "flag": "🇬🇶", "country_code": "GQ", "phone_code": 240, "min_length": 6, "max_length": 6},
  {"country_en": "Eritrea", "flag": "🇪🇷", "country_code": "ER", "phone_code": 291, "min_length": 7, "max_length": 7},
  {"country_en": "Estonia", "flag": "🇪🇪", "country_code": "EE", "phone_code": 372, "min_length": 8, "max_length": 8},
  {"country_en": "Ethiopia", "flag": "🇪🇹", "country_code": "ET", "phone_code": 251, "min_length": 9, "max_length": 9},
  {"country_en": "Falkland Islands (Malvinas)", "flag": "🇫🇰", "country_code": "FK", "phone_code": 500, "min_length": 5, "max_length": 5},
  {"country_en": "Faroe Islands", "flag": "🇫🇴", "country_code": "FO", "phone_code": 298, "min_length": 5, "max_length": 5},
  {"country_en": "Fiji", "flag": "🇫🇯", "country_code": "FJ", "phone_code": 679, "min_length": 7, "max_length": 7},
  {"country_en": "Finland", "flag": "🇫🇮", "country_code": "FI", "phone_code": 358, "min_length": 8, "max_length": 10},
  {"country_en": "France", "flag": "🇫🇷", "country_code": "FR", "phone_code": 33, "min_length": 9, "max_length": 9},
  {"country_en": "French Guiana", "flag": "🇬🇫", "country_code": "GF", "phone_code": 594, "min_length": 9, "max_length": 9},
  {"country_en": "French Polynesia", "flag": "🇵🇫", "country_code": "PF", "phone_code": 689, "min_length": 6, "max_length": 6},
  {"country_en": "French Southern Territories", "flag": "🇹🇫", "country_code": "TF", "phone_code": 262, "min_length": 15, "max_length": 15},
  {"country_en": "Gabon", "flag": "🇬🇦", "country_code": "GA", "phone_code": 241, "min_length": 7, "max_length": 7},
  {"country_en": "Gambia", "flag": "🇬🇲", "country_code": "GM", "phone_code": 220, "min_length": 7, "max_length": 7},
  {"country_en": "Georgia", "flag": "🇬🇪", "country_code": "GE", "phone_code": 995, "min_length": 9, "max_length": 9},
  {"country_en": "Germany", "flag": "🇩🇪", "country_code": "DE", "phone_code": 49, "min_length": 10, "max_length": 11},
  {"country_en": "Ghana", "flag": "🇬🇭", "country_code": "GH", "phone_code": 233, "min_length": 9, "max_length": 9},
  {"country_en": "Gibraltar", "flag": "🇬🇮", "country_code": "GI", "phone_code": 350, "min_length": 8, "max_length": 8},
  {"country_en": "Greece", "flag": "🇬🇷", "country_code": "GR", "phone_code": 30, "min_length": 10, "max_length": 10},
  {"country_en": "Greenland", "flag": "🇬🇱", "country_code": "GL", "phone_code": 299, "min_length": 6, "max_length": 6},
  {"country_en": "Grenada", "flag": "🇬🇩", "country_code": "GD", "phone_code": 1473, "min_length": 10, "max_length": 10},
  {"country_en": "Guadeloupe", "flag": "🇬🇵", "country_code": "GP", "phone_code": 590, "min_length": 15, "max_length": 15},
  {"country_en": "Guam", "flag": "🇬🇺", "country_code": "GU", "phone_code": 1671, "min_length": 10, "max_length": 10},
  {"country_en": "Guatemala", "flag": "🇬🇹", "country_code": "GT", "phone_code": 502, "min_length": 8, "max_length": 8},
  {"country_en": "Guernsey", "flag": "🇬🇬", "country_code": "GG", "phone_code": 44, "min_length": 10, "max_length": 10},
  {"country_en": "Guinea", "flag": "🇬🇳", "country_code": "GN", "phone_code": 224, "min_length": 9, "max_length": 9},
  {"country_en": "Guinea-Bissau", "flag": "🇬🇼", "country_code": "GW", "phone_code": 245, "min_length": 7, "max_length": 7},
  {"country_en": "Guyana", "flag": "🇬🇾", "country_code": "GY", "phone_code": 592, "min_length": 7, "max_length": 7},
  {"country_en": "Haiti", "flag": "🇭🇹", "country_code": "HT", "phone_code": 509, "min_length": 8, "max_length": 8},
  {"country_en": "Heard Island and Mcdonald Islands", "flag": "🇭🇲", "country_code": "HM", "phone_code": 672, "min_length": 15, "max_length": 15},
  {"country_en": "Holy See (Vatican City State)", "flag": "🇻🇦", "country_code": "VA", "phone_code": 379, "min_length": 10, "max_length": 10},
  {"country_en": "Honduras", "flag": "🇭🇳", "country_code": "HN", "phone_code": 504, "min_length": 8, "max_length": 8},
  {"country_en": "Hong Kong", "flag": "🇭🇰", "country_code": "HK", "phone_code": 852, "min_length": 8, "max_length": 8},
  {"country_en": "Hungary", "flag": "🇭🇺", "country_code": "HU", "phone_code": 36, "min_length": 9, "max_length": 9},
  {"country_en": "Iceland", "flag": "🇮🇸", "country_code": "IS", "phone_code": 354, "min_length": 9, "max_length": 9},
  {"country_en": "India", "flag": "🇮🇳", "country_code": "IN", "phone_code": 91, "min_length": 10, "max_length": 10},
  {"country_en": "Indonesia", "flag": "🇮🇩", "country_code": "ID", "phone_code": 62, "min_length": 9, "max_length": 11},
  {"country_en": "Iran", "flag": "🇮🇷", "country_code": "IR", "phone_code": 98, "min_length": 10, "max_length": 10},
  {"country_en": "Iraq", "flag": "🇮🇶", "country_code": "IQ", "phone_code": 964, "min_length": 10, "max_length": 10},
  {"country_en": "Ireland", "flag": "🇮🇪", "country_code": "IE", "phone_code": 353, "min_length": 9, "max_length": 9},
  {"country_en": "Isle of Man", "flag": "🇮🇲", "country_code": "IM", "phone_code": 44, "min_length": 10, "max_length": 10},
  {"country_en": "Israel", "flag": "🇮🇱", "country_code": "IL", "phone_code": 972, "min_length": 9, "max_length": 9},
  {"country_en": "Italy", "flag": "🇮🇹", "country_code": "IT", "phone_code": 39, "min_length": 9, "max_length": 13},
  {"country_en": "Jamaica", "flag": "🇯🇲", "country_code": "JM", "phone_code": 1876, "min_length": 10, "max_length": 10},
  {"country_en": "Japan", "flag": "🇯🇵", "country_code": "JP", "phone_code": 81, "min_length": 10, "max_length": 10},
  {"country_en": "Jersey", "flag": "🇯🇪", "country_code": "JE", "phone_code": 44, "min_length": 10, "max_length": 10},
  {"country_en": "Jordan", "flag": "🇯🇴", "country_code": "JO", "phone_code": 962, "min_length": 9, "max_length": 9},
  {"country_en": "Kazakhstan", "flag": "🇰🇿", "country_code": "KZ", "phone_code": 7, "min_length": 10, "max_length": 10},
  {"country_en": "Kenya", "flag": "🇰🇪", "country_code": "KE", "phone_code": 254, "min_length": 10, "max_length": 10},
  {"country_en": "Kiribati", "flag": "🇰🇮", "country_code": "KI", "phone_code": 686, "min_length": 8, "max_length": 8},
  {"country_en": "Korea, Democratic People's Republic of Korea", "flag": "🇰🇵", "country_code": "KP", "phone_code": 850, "min_length": 10, "max_length": 10},
  {"country_en": "Korea, Republic of South Korea", "flag": "🇰🇷", "country_code": "KR", "phone_code": 82, "min_length": 11, "max_length": 11},
  {"country_en": "Kosovo", "flag": "🇽🇰", "country_code": "XK", "phone_code": 383, "min_length": 8, "max_length": 8},
  {"country_en": "Kuwait", "flag": "🇰🇼", "country_code": "KW", "phone_code": 965, "min_length": 8, "max_length": 8},
  {"country_en": "Kyrgyzstan", "flag": "🇰🇬", "country_code": "KG", "phone_code": 996, "min_length": 9, "max_length": 9},
  {"country_en": "Laos", "flag": "🇱🇦", "country_code": "LA", "phone_code": 856, "min_length": 10, "max_length": 10},
  {"country_en": "Latvia", "flag": "🇱🇻", "country_code": "LV", "phone_code": 371, "min_length": 8, "max_length": 8},
  {"country_en": "Lebanon", "flag": "🇱🇧", "country_code": "LB", "phone_code": 961, "min_length": 8, "max_length": 8},
  {"country_en": "Lesotho", "flag": "🇱🇸", "country_code": "LS", "phone_code": 266, "min_length": 8, "max_length": 8},
  {"country_en": "Liberia", "flag": "🇱🇷", "country_code": "LR", "phone_code": 231, "min_length": 7, "max_length": 8},
  {"country_en": "Libyan Arab Jamahiriya", "flag": "🇱🇾", "country_code": "LY", "phone_code": 218, "min_length": 10, "max_length": 10},
  {"country_en": "Liechtenstein", "flag": "🇱🇮", "country_code": "LI", "phone_code": 423, "min_length": 7, "max_length": 7},
  {"country_en": "Lithuania", "flag": "🇱🇹", "country_code": "LT", "phone_code": 370, "min_length": 8, "max_length": 8},
  {"country_en": "Luxembourg", "flag": "🇱🇺", "country_code": "LU", "phone_code": 352, "min_length": 9, "max_length": 9},
  {"country_en": "Macao", "flag": "🇲🇴", "country_code": "MO", "phone_code": 853, "min_length": 8, "max_length": 8},
  {"country_en": "Macedonia", "flag": "🇲🇰", "country_code": "MK", "phone_code": 389, "min_length": 8, "max_length": 8},
  {"country_en": "Madagascar", "flag": "🇲🇬", "country_code": "MG", "phone_code": 261, "min_length": 10, "max_length": 10},
  {"country_en": "Malawi", "flag": "🇲🇼", "country_code": "MW", "phone_code": 265, "min_length": 9, "max_length": 9},
  {"country_en": "Malaysia", "flag": "🇲🇾", "country_code": "MY", "phone_code": 60, "min_length": 7, "max_length": 7},
  {"country_en": "Maldives", "flag": "🇲🇻", "country_code": "MV", "phone_code": 960, "min_length": 7, "max_length": 7},
  {"country_en": "Mali", "flag": "🇲🇱", "country_code": "ML", "phone_code": 223, "min_length": 8, "max_length": 8},
  {"country_en": "Malta", "flag": "🇲🇹", "country_code": "MT", "phone_code": 356, "min_length": 8, "max_length": 8},
  {"country_en": "Marshall Islands", "flag": "🇲🇭", "country_code": "MH", "phone_code": 692, "min_length": 7, "max_length": 7},
  {"country_en": "Martinique", "flag": "🇲🇶", "country_code": "MQ", "phone_code": 596, "min_length": 15, "max_length": 15},
  {"country_en": "Mauritania", "flag": "🇲🇷", "country_code": "MR", "phone_code": 222, "min_length": 8, "max_length": 8},
  {"country_en": "Mauritius", "flag": "🇲🇺", "country_code": "MU", "phone_code": 230, "min_length": 8, "max_length": 8},
  {"country_en": "Mayotte", "flag": "🇾🇹", "country_code": "YT", "phone_code": 262, "min_length": 9, "max_length": 9},
  {"country_en": "Mexico", "flag": "🇲🇽", "country_code": "MX", "phone_code": 52, "min_length": 10, "max_length": 10},
  {"country_en": "Micronesia, Federated States of Micronesia", "flag": "🇫🇲", "country_code": "FM", "phone_code": 691, "min_length": 7, "max_length": 7},
  {"country_en": "Moldova", "flag": "🇲🇩", "country_code": "MD", "phone_code": 373, "min_length": 8, "max_length": 8},
  {"country_en": "Monaco", "flag": "🇲🇨", "country_code": "MC", "phone_code": 377, "min_length": 8, "max_length": 8},
  {"country_en": "Mongolia", "flag": "🇲🇳", "country_code": "MN", "phone_code": 976, "min_length": 8, "max_length": 8},
  {"country_en": "Montenegro", "flag": "🇲🇪", "country_code": "ME", "phone_code": 382, "min_length": 8, "max_length": 8},
  {"country_en": "Montserrat", "flag": "🇲🇸", "country_code": "MS", "phone_code": 1664, "min_length": 10, "max_length": 10},
  {"country_en": "Morocco", "flag": "🇲🇦", "country_code": "MA", "phone_code": 212, "min_length": 9, "max_length": 9},
  {"country_en": "Mozambique", "flag": "🇲🇿", "country_code": "MZ", "phone_code": 258, "min_length": 12, "max_length": 12},
  {"country_en": "Myanmar", "flag": "🇲🇲", "country_code": "MM", "phone_code": 95, "min_length": 8, "max_length": 10},
  {"country_en": "Namibia", "flag": "🇳🇦", "country_code": "NA", "phone_code": 264, "min_length": 10, "max_length": 10},
  {"country_en": "Nauru", "flag": "🇳🇷", "country_code": "NR", "phone_code": 674, "min_length": 7, "max_length": 7},
  {"country_en": "Nepal", "flag": "🇳🇵", "country_code": "NP", "phone_code": 977, "min_length": 10, "max_length": 10},
  {"country_en": "Netherlands", "flag": "🇳🇱", "country_code": "NL", "phone_code": 31, "min_length": 9, "max_length": 9},
  {"country_en": "Netherlands Antilles", "flag": "", "country_code": "AN", "phone_code": 599, "min_length": 8, "max_length": 8},
  {"country_en": "New Caledonia", "flag": "🇳🇨", "country_code": "NC", "phone_code": 687, "min_length": 6, "max_length": 6},
  {"country_en": "New Zealand", "flag": "🇳🇿", "country_code": "NZ", "phone_code": 64, "min_length": 8, "max_length": 10},
  {"country_en": "Nicaragua", "flag": "🇳🇮", "country_code": "NI", "phone_code": 505, "min_length": 8, "max_length": 8},
  {"country_en": "Niger", "flag": "🇳🇪", "country_code": "NE", "phone_code": 227, "min_length": 8, "max_length": 8},
  {"country_en": "Nigeria", "flag": "🇳🇬", "country_code": "NG", "phone_code": 234, "min_length": 8, "max_length": 8},
  {"country_en": "Niue", "flag": "🇳🇺", "country_code": "NU", "phone_code": 683, "min_length": 4, "max_length": 4},
  {"country_en": "Norfolk Island", "flag": "🇳🇫", "country_code": "NF", "phone_code": 672, "min_length": 6, "max_length": 6},
  {"country_en": "Northern Mariana Islands", "flag": "🇲🇵", "country_code": "MP", "phone_code": 1670, "min_length": 7, "max_length": 7},
  {"country_en": "Norway", "flag": "🇳🇴", "country_code": "NO", "phone_code": 47, "min_length": 8, "max_length": 8},
  {"country_en": "Oman", "flag": "🇴🇲", "country_code": "OM", "phone_code": 968, "min_length": 8, "max_length": 8},
  {"country_en": "Pakistan", "flag": "🇵🇰", "country_code": "PK", "phone_code": 92, "min_length": 10, "max_length": 10},
  {"country_en": "Palau", "flag": "🇵🇼", "country_code": "PW", "phone_code": 680, "min_length": 7, "max_length": 7},
  {"country_en": "Palestinian Territory, Occupied", "flag": "🇵🇸", "country_code": "PS", "phone_code": 970, "min_length": 9, "max_length": 9},
  {"country_en": "Panama", "flag": "🇵🇦", "country_code": "PA", "phone_code": 507, "min_length": 8, "max_length": 8},
  {"country_en": "Papua New Guinea", "flag": "🇵🇬", "country_code": "PG", "phone_code": 675, "min_length": 8, "max_length": 8},
  {"country_en": "Paraguay", "flag": "🇵🇾", "country_code": "PY", "phone_code": 595, "min_length": 9, "max_length": 9},
  {"country_en": "Peru", "flag": "🇵🇪", "country_code": "PE", "phone_code": 51, "min_length": 9, "max_length": 9},
  {"country_en": "Philippines", "flag": "🇵🇭", "country_code": "PH", "phone_code": 63, "min_length": 10, "max_length": 10},
  {"country_en": "Pitcairn", "flag": "🇵🇳", "country_code": "PN", "phone_code": 64, "min_length": 10, "max_length": 10},
  {"country_en": "Poland", "flag": "🇵🇱", "country_code": "PL", "phone_code": 48, "min_length": 9, "max_length": 9},
  {"country_en": "Portugal", "flag": "🇵🇹", "country_code": "PT", "phone_code": 351, "min_length": 9, "max_length": 9},
  {"country_en": "Puerto Rico", "flag": "🇵🇷", "country_code": "PR", "phone_code": 1939, "min_length": 10, "max_length": 10},
  {"country_en": "Qatar", "flag": "🇶🇦", "country_code": "QA", "phone_code": 974, "min_length": 8, "max_length": 8},
  {"country_en": "Romania", "flag": "🇷🇴", "country_code": "RO", "phone_code": 40, "min_length": 10, "max_length": 10},
  {"country_en": "Russia", "flag": "🇷🇺", "country_code": "RU", "phone_code": 7, "min_length": 10, "max_length": 10},
  {"country_en": "Rwanda", "flag": "🇷🇼", "country_code": "RW", "phone_code": 250, "min_length": 9, "max_length": 9},
  {"country_en": "Reunion", "flag": "🇷🇪", "country_code": "RE", "phone_code": 262, "min_length": 9, "max_length": 9},
  {"country_en": "Saint Barthelemy", "flag": "🇧🇱", "country_code": "BL", "phone_code": 590, "min_length": 6, "max_length": 6},
  {"country_en": "Saint Helena, Ascension and Tristan Da Cunha", "flag": "🇸🇭", "country_code": "SH", "phone_code": 290, "min_length": 4, "max_length": 4},
  {"country_en": "Saint Kitts and Nevis", "flag": "🇰🇳", "country_code": "KN", "phone_code": 1869, "min_length": 10, "max_length": 10},
  {"country_en": "Saint Lucia", "flag": "🇱🇨", "country_code": "LC", "phone_code": 1758, "min_length": 10, "max_length": 10},
  {"country_en": "Saint Martin", "flag": "🇲🇫", "country_code": "MF", "phone_code": 590, "min_length": 9, "max_length": 9},
  {"country_en": "Saint Pierre and Miquelon", "flag": "🇵🇲", "country_code": "PM", "phone_code": 508, "min_length": 6, "max_length": 6},
  {"country_en": "Saint Vincent and the Grenadines", "flag": "🇻🇨", "country_code": "VC", "phone_code": 1784, "min_length": 10, "max_length": 10},
  {"country_en": "Samoa", "flag": "🇼🇸", "country_code": "WS", "phone_code": 685, "min_length": 5, "max_length": 5},
  {"country_en": "San Marino", "flag": "🇸🇲", "country_code": "SM", "phone_code": 378, "min_length": 10, "max_length": 10},
  {"country_en": "Sao Tome and Principe", "flag": "🇸🇹", "country_code": "ST", "phone_code": 239, "min_length": 7, "max_length": 7},
  {"country_en": "Saudi Arabia", "flag": "🇸🇦", "country_code": "SA", "phone_code": 966, "min_length": 9, "max_length": 9},
  {"country_en": "Senegal", "flag": "🇸🇳", "country_code": "SN", "phone_code": 221, "min_length": 9, "max_length": 9},
  {"country_en": "Serbia", "flag": "🇷🇸", "country_code": "RS", "phone_code": 381, "min_length": 8, "max_length": 9},
  {"country_en": "Seychelles", "flag": "🇸🇨", "country_code": "SC", "phone_code": 248, "min_length": 7, "max_length": 7},
  {"country_en": "Sierra Leone", "flag": "🇸🇱", "country_code": "SL", "phone_code": 232, "min_length": 6, "max_length": 6},
  {"country_en": "Singapore", "flag": "🇸🇬", "country_code": "SG", "phone_code": 65, "min_length": 8, "max_length": 8},
  {"country_en": "Slovakia", "flag": "🇸🇰", "country_code": "SK", "phone_code": 421, "min_length": 9, "max_length": 9},
  {"country_en": "Slovenia", "flag": "🇸🇮", "country_code": "SI", "phone_code": 386, "min_length": 9, "max_length": 9},
  {"country_en": "Solomon Islands", "flag": "🇸🇧", "country_code": "SB", "phone_code": 677, "min_length": 7, "max_length": 7},
  {"country_en": "Somalia", "flag": "🇸🇴", "country_code": "SO", "phone_code": 252, "min_length": 7, "max_length": 8},
  {"country_en": "South Africa", "flag": "🇿🇦", "country_code": "ZA", "phone_code": 27, "min_length": 9, "max_length": 9},
  {"country_en": "South Sudan", "flag": "🇸🇸", "country_code": "SS", "phone_code": 211, "min_length": 9, "max_length": 9},
  {"country_en": "South Georgia and the South Sandwich Islands", "flag": "🇬🇸", "country_code": "GS", "phone_code": 500, "min_length": 15, "max_length": 15},
  {"country_en": "Spain", "flag": "🇪🇸", "country_code": "ES", "phone_code": 34, "min_length": 9, "max_length": 9},
  {"country_en": "Sri Lanka", "flag": "🇱🇰", "country_code": "LK", "phone_code": 94, "min_length": 7, "max_length": 7},
  {"country_en": "Sudan", "flag": "🇸🇩", "country_code": "SD", "phone_code": 249, "min_length": 7, "max_length": 7},
  {"country_en": "Suriname", "flag": "🇸🇷", "country_code": "SR", "phone_code": 597, "min_length": 6, "max_length": 7},
  {"country_en": "Svalbard and Jan Mayen", "flag": "🇸🇯", "country_code": "SJ", "phone_code": 47, "min_length": 8, "max_length": 8},
  {"country_en": "Eswatini", "flag": "🇸🇿", "country_code": "SZ", "phone_code": 268, "min_length": 8, "max_length": 8},
  {"country_en": "Sweden", "flag": "🇸🇪", "country_code": "SE", "phone_code": 46, "min_length": 7, "max_length": 10},
  {"country_en": "Switzerland", "flag": "🇨🇭", "country_code": "CH", "phone_code": 41, "min_length": 9, "max_length": 9},
  {"country_en": "Syrian Arab Republic", "flag": "🇸🇾", "country_code": "SY", "phone_code": 963, "min_length": 9, "max_length": 9},
  {"country_en": "Taiwan", "flag": "🇹🇼", "country_code": "TW", "phone_code": 886, "min_length": 9, "max_length": 9},
  {"country_en": "Tajikistan", "flag": "🇹🇯", "country_code": "TJ", "phone_code": 992, "min_length": 4, "max_length": 9},
  {"country_en": "Tanzania, United Republic of Tanzania", "flag": "🇹🇿", "country_code": "TZ", "phone_code": 255, "min_length": 6, "max_length": 6},
  {"country_en": "Thailand", "flag": "🇹🇭", "country_code": "TH", "phone_code": 66, "min_length": 9, "max_length": 9},
  {"country_en": "Timor-Leste", "flag": "🇹🇱", "country_code": "TL", "phone_code": 670, "min_length": 8, "max_length": 8},
  {"country_en": "Togo", "flag": "🇹🇬", "country_code": "TG", "phone_code": 228, "min_length": 8, "max_length": 8},
  {"country_en": "Tokelau", "flag": "🇹🇰", "country_code": "TK", "phone_code": 690, "min_length": 4, "max_length": 4},
  {"country_en": "Tonga", "flag": "🇹🇴", "country_code": "TO", "phone_code": 676, "min_length": 7, "max_length": 7},
  {"country_en": "Trinidad and Tobago", "flag": "🇹🇹", "country_code": "TT", "phone_code": 1868, "min_length": 10, "max_length": 10},
  {"country_en": "Tunisia", "flag": "🇹🇳", "country_code": "TN", "phone_code": 216, "min_length": 8, "max_length": 8},
  {"country_en": "Turkey", "flag": "🇹🇷", "country_code": "TR", "phone_code": 90, "min_length": 10, "max_length": 10},
  {"country_en": "Turkmenistan", "flag": "🇹🇲", "country_code": "TM", "phone_code": 993, "min_length": 8, "max_length": 8},
  {"country_en": "Turks and Caicos Islands", "flag": "🇹🇨", "country_code": "TC", "phone_code": 1649, "min_length": 10, "max_length": 10},
  {"country_en": "Tuvalu", "flag": "🇹🇻", "country_code": "TV", "phone_code": 688, "min_length": 5, "max_length": 5},
  {"country_en": "Uganda", "flag": "🇺🇬", "country_code": "UG", "phone_code": 256, "min_length": 12, "max_length": 12},
  {"country_en": "Ukraine", "flag": "🇺🇦", "country_code": "UA", "phone_code": 380, "min_length": 9, "max_length": 9},
  {"country_en": "United Arab Emirates", "flag": "🇦🇪", "country_code": "AE", "phone_code": 971, "min_length": 9, "max_length": 9},
  {"country_en": "United Kingdom", "flag": "🇬🇧", "country_code": "GB", "phone_code": 44, "min_length": 10, "max_length": 10},
  {"country_en": "United States", "flag": "🇺🇸", "country_code": "US", "phone_code": 1, "min_length": 10, "max_length": 10},
  {"country_en": "Uruguay", "flag": "🇺🇾", "country_code": "UY", "phone_code": 598, "min_length": 8, "max_length": 8},
  {"country_en": "Uzbekistan", "flag": "🇺🇿", "country_code": "UZ", "phone_code": 998, "min_length": 9, "max_length": 9},
  {"country_en": "Vanuatu", "flag": "🇻🇺", "country_code": "VU", "phone_code": 678, "min_length": 6, "max_length": 6},
  {"country_en": "Venezuela, Bolivarian Republic of Venezuela", "flag": "🇻🇪", "country_code": "VE", "phone_code": 58, "min_length": 7, "max_length": 7},
  {"country_en": "Vietnam", "flag": "🇻🇳", "country_code": "VN", "phone_code": 84, "min_length": 9, "max_length": 9},
  {"country_en": "Virgin Islands, British", "flag": "🇻🇬", "country_code": "VG", "phone_code": 1284, "min_length": 10, "max_length": 10},
  {"country_en": "Virgin Islands, U.S.", "flag": "🇻🇮", "country_code": "VI", "phone_code": 1340, "min_length": 10, "max_length": 10},
  {"country_en": "Wallis and Futuna", "flag": "🇼🇫", "country_code": "WF", "phone_code": 681, "min_length": 4, "max_length": 6},
  {"country_en": "Yemen", "flag": "🇾🇪", "country_code": "YE", "phone_code": 967, "min_length": 9, "max_length": 9},
  {"country_en": "Zambia", "flag": "🇿🇲", "country_code": "ZM", "phone_code": 260, "min_length": 9, "max_length": 9},
  {"country_en": "Zimbabwe", "flag": "🇿🇼", "country_code": "ZW", "phone_code": 263, "min_length": 9, "max_length": 9}
];
